accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name='accounts'
urlpatterns = [
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    path('loginpage/',
         auth_views.LoginView.as_view(template_name='loginpage.html'),
         name='loginpage'
         ),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

gamelog/urls.py
from django.urls import path
from . import views

app_name='gamelog'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('login/',views.LoginView.as_view(),name='login'),
    path(
        'contact/',
        views.ContactView.as_view(),
        name='contact'
    ),
    path(
        'post/',
        views.CreateGamelogView.as_view(),
        name='post'),
    path(
        'post_done/',
        views.PostSuccessView.as_view(),
        name='post_done'),
    path(
        'content/',
        views.ContentView.as_view(),
        name='content'
    ),
    path('content/<int:Category>',
         views.CategoryView.as_view(),
         name='games_cat'
         ),
    path('user-list/<int:user>',
         views.UserView.as_view(),
         name='user_list'
         ),
    path('game-detail/<int:pk>',
         views.DetailView.as_view(),
         name='game_detail'),
    path('mypage/',
         views.MypageView.as_view(),
         name='mypage'),
    path('game-detail/<int:pk>/delete',
         views.GameDeleteView.as_view(),
         name='game_delete'),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gamelog.urls')),
    path('',include('accounts.urls')),
]
urlpatterns+=static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

gamelog/models.py
from django.db import models

# Create your models here.
from accounts.models import CustomUser

class Category(models.Model):
    title=models.CharField(
        verbose_name='カテゴリ',
        max_length=20)
    
    def __str__(self):
        return self.title
    
class GamePost(models.Model):
    user=models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )
    Category=models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
    )
    title=models.CharField(
        verbose_name='タイトル',
        max_length=200
    )
    content=models.TextField(
        verbose_name='コメント',
    )
    image1=models.ImageField(
        verbose_name='イメージ1',
        upload_to='photo'
    )
    posted_at=models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )
    
    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=CustomUser
        fields=('username','email','password1','password2')

gamelog/forms.py
from django import forms
from django.forms import ModelForm
from .models import GamePost

class ContactForm(forms.Form):
    name=forms.CharField(label='お名前')
    email=forms.EmailField(label='メールアドレス')
    title=forms.CharField(label='件名')
    message=forms.CharField(label='メッセージ',widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder']=\
            'お名前を入力してください'
        self.fields['name'].widget.attrs['class']='form-control'
        
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder']=\
            'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class']='form-control'
        
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder']=\
            'タイトルを入力してください'
        self.fields['title'].widget.attrs['class']='form-control'
        
        super().__init__(*args, **kwargs)
        self.fields['message'].widget.attrs['placeholder']=\
            'メッセージを入力してください'
        self.fields['message'].widget.attrs['class']='form-control'

class GamePostForm(ModelForm):
    class Meta:
        model=GamePost
        fields=['Category','title','content','image1']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

# Create your views here.

class SignUpView(CreateView):
    form_class=CustomUserCreationForm
    template_name='signup.html'
    success_url=reverse_lazy('accounts:signup_success')
    
    def form_valid(self, form):
        user=form.save()
        self.object = user
        return super().form_valid(form)
    
class SignUpSuccessView(TemplateView):
    template_name="signup_success.html"

gamelog/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, ListView, DetailView

from django.views.generic import FormView, CreateView, DeleteView

from django.urls import reverse_lazy

from .forms import ContactForm, GamePostForm

from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required

from django.contrib import messages

from django.core.mail import EmailMessage

from .models import GamePost

class IndexView(TemplateView):
    template_name='index.html'
    
class LoginView(TemplateView):
    template_name='login.html'
    
class ContactView(FormView):
    template_name='contact.html'
    form_class=ContactForm
    success_url=reverse_lazy('gamelog:contact')
    def form_valid(self, form):
        name=form.cleaned_data['name']
        email=form.cleaned_data['email']
        title=form.cleaned_data['title']
        message=form.cleaned_data['message']
        subject='お問い合わせ:{}'.format(title)
        message=\
            '送信者名:{0}\nメールアドレス:{1}\n タイトル:{2}\n メッセージ:\n{3}' \
                .format(name, email, title, message)
        from_email='admin@example.com'
        to_list=['admin@example.com']
        message=EmailMessage(subject=subject,
                             body=message,
                             from_email=from_email,
                             to=to_list,
                             )
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました'
        )
        return super().form_valid(form)
    
@method_decorator(login_required, name='dispatch')
class CreateGamelogView(CreateView):
    form_class=GamePostForm
    template_name="post_game.html"
    success_url=reverse_lazy('gamelog:post_done')
    
    def form_valid(self, form):
        postdata=form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)
    
class PostSuccessView(TemplateView):
    template_name='post_success.html'
    
class ContentView(ListView):
    
    template_name='content.html'
    queryset=GamePost.objects.order_by('-posted_at')
    paginate_by=5

class CategoryView(ListView):
    template_name='content.html'
    paginate_by=5
    def get_queryset(self):
        category_id=self.kwargs['Category']
        categories=GamePost.objects.filter(
            Category=category_id).order_by('-posted_at')
        return categories
    
class UserView(ListView):
    template_name='content.html'
    paginate_by=5
    def get_queryset(self):
        user_id=self.kwargs['user']
        user_list=GamePost.objects.filter(
            user=user_id).order_by('-posted_at')
        return user_list
    
class DetailView(DetailView):
    template_name='detail.html'
    model=GamePost
    
class MypageView(ListView):
    template_name='mypage.html'
    paginate_by=5
    
    def get_queryset(self):
        queryset=GamePost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        return queryset
    
class GameDeleteView(DeleteView):
    model=GamePost
    template_name='game_delete.html'
    success_url=reverse_lazy('gamelog:mypage')
    def delete(self, request,*args,**kwargs):
        return super().delete(request,*args, **kwargs)

accounts/templates/logout.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Log out{% endblock %}

      {% block header %}
      <div class="container px-4 px-lg-5 h-100">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-end">
                <h1 class="text-white font-weight-bold">ログアウトが完了しました</h1>
                <hr class="divider" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <a class="text-white-100 mb-4" href={%url 'gamelog:index'%}>メインページに戻る</a>
            </div>
        </div>
      {% endblock %}

gamelog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico"%} />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href={%url 'gamelog:index'%}>GUIDE BOOK WIKI</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        {%if user.is_authenticated%}
                        <li class="nav-item"><a class="nav-link" href={% url 'gamelog:mypage' %}>Mypage</a></li>
                        <li class="nav-item"><a class="nav-link" href={% url 'gamelog:content' %}>Content</a></li>
                        <li class="nav-item"><a class="nav-link" href={% url 'gamelog:contact' %}>Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href={% url 'gamelog:post' %}>Post</a></li>
                        <li class="nav-item"><a class="nav-link" href={% url 'accounts:logout'%}>Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href={% url 'gamelog:index' %}>About</a></li>
                        <li class="nav-item"><a class="nav-link" href={% url 'gamelog:index' %}>Content</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">Game</a></li>
                        <li class="nav-item"><a class="nav-link" href={%url 'gamelog:login'%}>Login</a></li>
                        {%endif%}
                    </ul>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            {%block header%}{%endblock%}
        </header>
        <body>
            {%block contents%}{%endblock%}
        </body>
        <!-- Call to action-->
        <main>
            {% block main %}{% endblock main %}
        </main>
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-4 text-center mb-5 mb-lg-0">
                        <i class="bi-phone fs-2 mb-3 text-muted"></i>
                        <div></div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2024 - Itou</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

gamelog/templates/content copy.html
    <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {%for record in object_list%}
                    <div class="post-preview">
                        <img src="{{record.image1.url}}"
                            class="bd-placeholder-image card-img-top"
                            width="100%" height="225"
                            xmlns="http://www.w3.org/2000/svg"
                            role="img" aria-label="placeholder: Thumbnail"
                            preserveAspectRatio="xMidYMid slice"
                            focusable="false">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c"/>
                        </img>
                        <div class="card-body">
                            <p class="card-text">
                                {{record.title}}
                            </p>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{%url 'gamelog:game_detail' record.pk%}'">
                                    View
                                </button>
                                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{%url 'gamelog:games_cat' Category=record.Category.id%}'">
                                    {{record.Category.title}}
                                </button>
                            </div>
                            <a href="{% url 'gamelog:user_list' user=record.user.id %}">
                                <small class="text-muted">
                                    {{record.user.username}}</small>
                            </a>
                        </div>
                        <hr class="divider" />
                    </div>
                    <hr class="my-4" />
                    {% endfor %}
                    <div class="d-flex justify-content-end mb-4">
                        <a class="btn btn-primary text-uppercase" href="#!">
                            Older Posts →
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
  

gamelog/templates/content.html
{% extends "base.html" %}
{% load static %}


{% block title %}ゲームWIKI {% endblock title %}
{%block header%}
<div class="container px-4 px-lg-5 h-100">
    <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-8 align-self-end">
            <h1 class="text-white font-weight-bold">攻略掲示板</h1>
            <hr class="divider" />
        </div>
        <div class="col-lg-8 align-self-baseline">
            <p class="text-white-75 mb-5">情報を共有しあいましょう！</p>
            <a class="btn btn-primary btn-xl" href="#about">掲示板を見る</a>
            <a class="btn btn-primary btn-xl" href={%url 'gamelog:post'%}>投稿する</a>
        </div>
    </div>
</div>
{%endblock header%}
{%block contents%}
{% include "pagination.html" %}
    <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {%for record in object_list%}
                    <div class="post-preview">
                        <img src="{{record.image1.url}}"
                            class="bd-placeholder-image card-img-top"
                            width="100%" height="225"
                            xmlns="http://www.w3.org/2000/svg"
                            role="img" aria-label="placeholder: Thumbnail"
                            preserveAspectRatio="xMidYMid slice"
                            focusable="false">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c"/>
                        </img>
                        <div class="card-body">
                            <p class="card-text">
                                {{record.title}}
                            </p>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{%url 'gamelog:game_detail' record.pk%}'">
                                    View
                                </button>
                                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{%url 'gamelog:games_cat' Category=record.Category.id%}'">
                                    {{record.Category.title}}
                                </button>
                            </div>
                            <a href="{% url 'gamelog:user_list' user=record.user.id %}">
                                <small class="text-muted">
                                    {{record.user.username}}</small>
                            </a>
                        </div>
                        <hr class="divider" />
                    </div>
                    <hr class="my-4" />
                    {% endfor %}
                    <div class="d-flex justify-content-end mb-4">
                        <a class="btn btn-primary text-uppercase" href="#!">
                            Older Posts →
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
        <!-- Portfolio-->
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={%url 'gamelog:games_cat' Category=1%} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/minecraft.jpg" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">category</div>
                                <div class="project-name">Minecraft</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=3%} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/mh.jpg" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Monstar Hunter</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=5 %} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/Fortnite.jpg" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Fortnite</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=2 %} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/pokemon.jpg" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Pokemon</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=4 %} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/mario.png" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Super Mario</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=6 %} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/valorant.png" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Valorant</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
{%endblock%}
</html>

gamelog/templates/detail.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}
{%block header%}
<div class="container px-4 px-lg-5 h-100">
    <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-8 align-self-end">
            <h1 class="text-white font-weight-bold">{{object.title}}</h1>
            <hr class="divider" />
        </div>
        <div class="col-lg-8 align-self-baseline">
            <p class="text-white-75 mb-5">投稿者：{{object.user}}</p>
            <a class="btn btn-primary btn-xl" href="#about">掲示板を見る</a>
            <a class="btn btn-primary btn-xl" href={%url 'gamelog:post'%}>投稿する</a>
        </div>
    </div>
</div>
{%endblock header%}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <p>{{object.content}}</p>
            <br>
            <p>{{object.posted_at}}に投稿</p>
            <p><img src="{{object.image1.url}}"
                class="bd-placeholder-image card-img-top"
                preserveAspectRatio="xMidYMid slice"></img></p>
            {% if request.user == object.user %}
            <form method="POST">
                <a href="{% url 'gamelog:game_delete' object.pk %}"
                    class="btn btn-primary my-2">削除する</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

gamelog/templates/index.html
{% extends "base.html" %}
{% load static %}


{% block title %}ゲームWIKI {% endblock title %}
{%block header%}
<div class="container px-4 px-lg-5 h-100">
    <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-8 align-self-end">
            <h1 class="text-white font-weight-bold">ゲームWIKIへようこそ</h1>
            <hr class="divider" />
        </div>
        <div class="col-lg-8 align-self-baseline">
            <p class="text-white-75 mb-5">ここでは様々なゲームに関する攻略情報をお届けしていきます！</p>
            <a class="btn btn-primary btn-xl" href="#about">情報を探してみる</a>
        </div>
    </div>
</div>
{%endblock header%}
    {%block contents%}
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">必要な情報がすべてここに</h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">最新のゲームから昔懐かしのレトロゲームまで、すべての攻略がここに乗っています</p>
                        <a class="btn btn-light btn-xl" href="#services">始めてみる</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Services-->
        <!-- Portfolio-->
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={%url 'gamelog:games_cat' Category=1%} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/minecraft.jpg" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Minecraft</div>
                                <div class="project-name">Minecraft</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=3%} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/mh.jpg" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Monstar Hunter</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=5 %}  title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/Fortnite.jpg" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Fortnite</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=2 %}  title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/pokemon.jpg" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Pokemon</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=4 %} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/mario.png" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Super Mario</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href={% url 'gamelog:games_cat' Category=6 %} title="Project Name">
                            <img class="img-fluid" src={% static "assets/img/portfolio/thumbnails/valorant.png" %} alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Category</div>
                                <div class="project-name">Valorant</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {%endblock%}
    {%block main%}
        <!-- Call to action-->
        <section class="page-section bg-dark text-white">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mb-4">登録はこちらから</h2>
                <a class="btn btn-light btn-xl" href={%url 'gamelog:login'%}>アカウント登録</a>
            </div>
        </section>
        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6 text-center">
                        <a class="btn btn-light btn-xl" href={%url 'gamelog:login'%}><h2>お問い合わせ</h2></a>
                        <p class="text-muted mb-5">お問い合わせやご連絡などがございました上のフォームからご連絡ください</p>
                    </div>
                </div>
    {%endblock%}
        <!-- Footer-->
</html>